<template>
    <div id="faq">
        <div>
            <h1>Membership</h1>
        </div>
        <div class="q">
            <input type="checkbox" id="faq1" />
            <label class="panel-label" for="faq1">
                <h2>How does Channel membership work?</h2>
            </label>
            <div class="a">
                <p>Channel makes it possible to subscribe to groups of creators ("bundles"), receiving all of the content they produce in a single RSS stream. Membership is facilitated by web3 using a Channel member token (either the Founder or General NFT) that is bought and stored in a <a href="#wallet">wallet</a>, and then by connecting that wallet here. General membership is seasonal, auto-renewing every few months. Founder membership is open-ended (i.e., 'for life').</p>
            </div>
        </div>
        <div class="q">
            <input type="checkbox" id="faq2" />
            <label class="panel-label" for="faq2">
                <h2>What are the benefits of a Channel membership?</h2>
            </label>
            <div class="a">
                <p>Subscribing to a bundle (once holding a Founder or General member token) gives access to a cluster of related creators all in one place. With that access, also comes the ability to apply to the creators' sub-communities (currently hosted on Discord). Upon joining Channel, subscribers are issued a membership card that allows users worldwide to collect, own, and trade blockchain-based badges, which can grant entry to special spaces, projects, and events (both digital and irl).</p>
            </div>
        </div>
        <div class="q">
            <input type="checkbox" id="faq3" />
            <label class="panel-label" for="faq3">
                <h2>What is a "season"?</h2>
            </label>
            <div class="a">
                <p>Similar to "quarters" but more flexible, Channel "seasons" carry the double valence of organizational and editorial development. On average, a season will last 3-4 months, with the exact length contingent on both the time needed to implement new structures/tech as well as the external vibes/economic/political conditions influencing our content. </p>
            </div>
        </div>
        <div class="q">
            <input type="checkbox" id="faq4" />
            <label class="panel-label" for="faq4">
                <h2>What exactly is the Channel "General" token and how much does it cost?</h2>
            </label>
            <div class="a">
                <p>Holding a "General" token allows users to subscribe to a bundle. This token is recharged each season through an auto-renewal process. The rate of purchase and renewal is set to a stable $USD amount and the cost is less than subscribing to all three creators individually via existing platforms. </p>
            </div>
        </div>
        <div class="q">
            <input type="checkbox" id="faq5" />
            <label class="panel-label" for="faq5">
                <h2>What's special about the Channel "Founder" token and how much does it cost?</h2>
            </label>
            <div class="a">
                <p>In a sense, the Founder token is a membership encompassing both the Channel creator network and the Channel protocol. Holders receive open-ended access to all Channel creator content, across all bundles — as well as a voice in Channel's development and its progressive decentralization. In this spirit, Founders are given prioritized access to new platform features as well as direct access to the engineers. The s0 Founder collection features art by Team Rolfes and is traded on Zora and OpenSea. The funds and community generated by this initial Founder collection enable us to build out the Channel tool set and distribute it broadly. </p>
            </div>
        </div>
        <div>
            <h1>Creators</h1>
        </div>
        <div class="q">
            <input type="checkbox" id="faq6" />
            <label class="panel-label" for="faq6">
                <h2>Can my podcast / publication start using Channel?</h2>
            </label>
            <div class="a">
                <p>Yes, we are still in our alpha development phases with our core set of creators. Later this year we will be opening up the protocol for public use. Sign up for our <mailing list=""> for more updates.</mailing></p>
            </div>
        </div>
        <div class="q">
            <input type="checkbox" id="faq7" />
            <label class="panel-label" for="faq7">
                <h2>Does Channel only support audio/RSS/podcasts?</h2>
            </label>
            <div class="a">
                <p>For now, yes. However, we have big plans for a broad set of economic and publishing tools for communities and creators.</p>
            </div>
            </div>
        <div class="q">
            <input type="checkbox" id="faq8" />
            <label class="panel-label" for="faq8">
                <h2>How will creator payouts work?</h2>
            </label>
            <div class="a">
                <p>N/A</p>
            </div>
        </div>
        <div class="q">
            <input type="checkbox" id="faq9" />
            <label class="panel-label" for="faq9">
                <h2>How will payment processing work?</h2>
            </label>
            <div class="a">
                <p>N/A</p>
            </div>
        </div>
        <div>
            <h1>Tech</h1>
        </div>
        <div class="q">
            <input type="checkbox" id="faq10" />
            <label class="panel-label" for="faq10">
                <h2>What chain are you building on?</h2>
            </label>
            <div class="a">
                <p>We're starting with an Ethereum compatible L2 solution (likely GnosisChain), with the intent of expanding our interoperability to as many chains as possible going forward. Optimally, we'll build on a chain that is carbon negative and developer friendly, has low transaction costs, and runs on a token pegged to $USD, which will ensure subscription rates remain stable/accessible.</p>
            </div>
        </div>
        <div class="q">
            <input type="checkbox" id="faq11" />
            <label class="panel-label" for="faq11">
                <h2>Why did you use Ethereum for s0?</h2>
            </label>
            <div class="a">
                <p>The main NFT market is located on Ethereum. Although L2s have advantages, an L2 launch would have caused unnecessary friction and worked against our aim of reaching a broad audience spanning both crypto natives and people coming to Web3 for the first time.</p>
            </div>
        </div>
        <div class="q">
            <input type="checkbox" id="faq12" />
            <label class="panel-label" for="faq12">
                <h2>Aren't NFTs minted by chopping down rainforests; why do you hate Mother Gaia?</h2>
            </label>
            <div class="a">
                <p>Ethereum is energy intensive, yes, but it uses a fixed amount of energy regardless of the volume of activity happening on the network — i.e., minting an NFT on the Ethereum network does not directly change the amount of energy used. But as we do care about our ecological impact, Channel itself will run on a proof-of-stake chain that consumes negligible energy. This has the coinciding benefit of keeping s1 subscriptions affordable (given the much lower gas fees). For accurate information about the relative energy costs of the Ethereum network, check out these Channel podcast discussions with prominent energy experts [1], [2]</p>
            </div>
        </div>
    </div>
</template>
  
<script>
  export default {
    name: 'FAQ'
}
</script>
  
<style scoped>
    #faq {
        max-width: 800px;
        margin: 0 auto;
        padding: 0 5%;
    }
    h1 {
        margin-top: 75px;
        margin-bottom: 50px;
        text-align: center;
        font-weight: 600;
    }
    h2 {
        margin-bottom: 0;
    }
    .a {
        margin-top: 13px;
        transition-timing-function: ease-out;
    }

    .q {
        overflow: hidden;
        width: 100%;
        border-bottom: 5px dotted black;
    }
    .panel-label {
        display: flex;
        justify-content: space-between;
        padding: 2rem 0 1rem;
        cursor: pointer;
        transition-timing-function: ease-out;
    }
    .panel-label::after {
        position: relative;
        top: -5px;
        right: 0;
        content: "+";
        font-family: "permanent marker";
        font-size: 2rem;
        transition: all .5s;
    }
    .a {
        max-height: 0;
        padding: 0 1em;
        transition: all .5s;
    }
    input:checked ~ .a {
        max-height: 100vh;
        padding: 1em;
    }
    input[type=checkbox] {
        display: none;
    }
</style>